"""Seed generator for Order of the Arrow lodges (entity layer).

The OA is Scouting America's honor society; each council charters one lodge (a few large
councils charter more). One file per lodge: data/oa-lodges/<slug>.json, as a versioned
entity so future renames/mergers (which track council mergers) become lifecycle events.

Source: the official OA lodge locator feed (oa-bsa.org/app/lodge-map/council_data.json),
snapshot 2026-07-21. Only public/organizational facts are kept — name, chartering
council (linked by council number, a few by council name), OA section/region, HQ city/state
+ coordinates, and lodge website. Lodge OFFICER NAMES and CONTACT EMAILS from the feed are
deliberately EXCLUDED as PII (especially youth officers). Lodge NUMBERS are not in the feed
(backfilled from lodge registries later). Records are baked below so this generator is
deterministic and reproduces the committed files byte-for-byte.
"""
from __future__ import annotations

import json
from pathlib import Path

FEED_URL = "https://oa-bsa.org/app/lodge-map/council_data.json"
VERIFIED_AT = "2026-07-21"
NOTES = ("Official OA lodge locator feed (snapshot 2026-07-21); chartering council linked by "
         "council number. Officer names and contact emails excluded as PII.")

LODGES = json.loads(r"""
[
  {
    "slug": "aal-pa-tah",
    "name": "Aal-Pa-Tah",
    "number": null,
    "council": "council:gulf-stream",
    "section": "E5",
    "region": "E",
    "hq_city": "Palm Beach Gardens",
    "hq_state": "FL",
    "lat": 26.7993434,
    "lon": -80.1072863,
    "website": "http://www.aalpatah.org"
  },
  {
    "slug": "abake-mi-sa-na-ki",
    "name": "Abake Mi-Sa-Na-Ki",
    "number": null,
    "council": "council:cape-cod-and-the-islands",
    "section": "E19",
    "region": "E",
    "hq_city": "Yarmouth Port",
    "hq_state": "MA",
    "lat": 41.689979,
    "lon": -70.2565912,
    "website": "http://www.scoutscapecod.org"
  },
  {
    "slug": "achewon-netopalis",
    "name": "Achewon Netopalis",
    "number": null,
    "council": "council:greenwich",
    "section": "E18",
    "region": "E",
    "hq_city": "Greenwich",
    "hq_state": "CT",
    "lat": 41.0302285,
    "lon": -73.62437179999999,
    "website": "http://www.achewonnetopalis.com"
  },
  {
    "slug": "achpateuny",
    "name": "Achpateuny",
    "number": null,
    "council": "council:far-east",
    "section": "G19",
    "region": "G",
    "hq_city": "FPO",
    "hq_state": "AP",
    "lat": 26.3168942,
    "lon": 127.7652535,
    "website": "http://www.oa803.org"
  },
  {
    "slug": "ah-tic",
    "name": "Ah'Tic",
    "number": null,
    "council": "council:bucktail",
    "section": "E21",
    "region": "E",
    "hq_city": "Penfield",
    "hq_state": "PA",
    "lat": 41.2212276,
    "lon": -78.6337592,
    "website": "http://www.oa.bucktail.org"
  },
  {
    "slug": "ahoalan-nachpikin",
    "name": "Ahoalan-Nachpikin",
    "number": null,
    "council": "council:chickasaw",
    "section": "E3",
    "region": "E",
    "hq_city": "Memphis",
    "hq_state": "TN",
    "lat": 35.1297543,
    "lon": -89.9772989,
    "website": "http://www.chickasawoa.org"
  },
  {
    "slug": "aina-topa-hutsi",
    "name": "Aina Topa Hutsi",
    "number": null,
    "council": "council:alamo-area",
    "section": "G2",
    "region": "G",
    "hq_city": "San Antonio",
    "hq_state": "TX",
    "lat": 29.5404758,
    "lon": -98.5280016,
    "website": "https://www.alamoareascouting.org/oa"
  },
  {
    "slug": "ajapeu",
    "name": "Ajapeu",
    "number": null,
    "council": "council:green-mountain",
    "section": "E20",
    "region": "E",
    "hq_city": "Waterbury",
    "hq_state": "VT",
    "lat": 44.3364912,
    "lon": -72.7551182,
    "website": "http://www.ajapeu351.org"
  },
  {
    "slug": "ajapeu-777",
    "name": "Ajapeu",
    "number": null,
    "council": "council:washington-crossing",
    "section": "E17",
    "region": "E",
    "hq_city": "Doylestown",
    "hq_state": "PA",
    "lat": 40.3068778,
    "lon": -75.1260665,
    "website": "http://www.ajapeu2.org"
  },
  {
    "slug": "akela-wahinapay",
    "name": "Akela Wahinapay",
    "number": null,
    "council": "council:caddo-area",
    "section": "G3",
    "region": "G",
    "hq_city": "Texarkana",
    "hq_state": "TX",
    "lat": 33.4634602,
    "lon": -94.06012609999999,
    "website": "http://www.lodge232.org"
  },
  {
    "slug": "alibamu",
    "name": "Alibamu",
    "number": null,
    "council": "council:tukabatchee-area",
    "section": "E6",
    "region": "E",
    "hq_city": "Montgomery",
    "hq_state": "AL",
    "lat": 32.350251,
    "lon": -86.26125069999999,
    "website": "https://alibamu.org"
  },
  {
    "slug": "allohak-menewi",
    "name": "Allohak Menewi",
    "number": null,
    "council": "council:laurel-highlands",
    "section": "E21",
    "region": "E",
    "hq_city": "Pittsburgh",
    "hq_state": "PA",
    "lat": 40.4434256,
    "lon": -79.99020829999999,
    "website": "http://lodge57.org"
  },
  {
    "slug": "amangamek-wipit",
    "name": "Amangamek-Wipit",
    "number": null,
    "council": "council:national-capital-area",
    "section": "E10",
    "region": "E",
    "hq_city": "Bethesda",
    "hq_state": "MD",
    "lat": 39.0069367,
    "lon": -77.09804249999999,
    "website": "https://wipit470.org"
  },
  {
    "slug": "amangi-nacha",
    "name": "Amangi Nacha",
    "number": null,
    "council": "council:golden-empire",
    "section": "G17N",
    "region": "G",
    "hq_city": "Sacramento",
    "hq_state": "CA",
    "lat": 38.641571,
    "lon": -121.4850767,
    "website": "http://amanginacha.org"
  },
  {
    "slug": "ammatdiio",
    "name": "Ammatdiio",
    "number": null,
    "council": "council:crossroads-of-the-west",
    "section": "G12S",
    "region": "G",
    "hq_city": "Ogden",
    "hq_state": "UT",
    "lat": 41.165223,
    "lon": -111.9495416,
    "website": "http://www.utahoa.org"
  },
  {
    "slug": "anpetu-we",
    "name": "Anpetu-We",
    "number": null,
    "council": "council:greater-saint-louis-area",
    "section": "G7",
    "region": "G",
    "hq_city": "Chesterfield",
    "hq_state": "MO",
    "lat": 38.6291495,
    "lon": -90.5184984,
    "website": "http://www.anpetu-we.org"
  },
  {
    "slug": "anpetu-we-nisha-kittan-shawnee-woapink",
    "name": "Anpetu-We / Nisha Kittan / Shawnee / Woapink",
    "number": null,
    "council": "council:greater-saint-louis-area",
    "section": "G7",
    "region": "G",
    "hq_city": "Chesterfield",
    "hq_state": "MO",
    "lat": 38.6291495,
    "lon": -90.5184984,
    "website": null
  },
  {
    "slug": "apoxky-aio",
    "name": "Apoxky Aio",
    "number": null,
    "council": "council:montana",
    "section": "G12N",
    "region": "G",
    "hq_city": "Great Falls",
    "hq_state": "MT",
    "lat": 47.4872212,
    "lon": -111.2927662,
    "website": "https://www.apoxkyaio.com"
  },
  {
    "slug": "aracoma",
    "name": "Aracoma",
    "number": null,
    "council": "council:black-warrior",
    "section": "E6",
    "region": "E",
    "hq_city": "Tuscaloosa",
    "hq_state": "AL",
    "lat": 33.2119155,
    "lon": -87.5724137,
    "website": "http://www.aracoma481.org"
  },
  {
    "slug": "ashwanchi-kinta",
    "name": "Ashwanchi Kinta",
    "number": null,
    "council": "council:choctaw-area",
    "section": "E4",
    "region": "E",
    "hq_city": "Meridian",
    "hq_state": "MS",
    "lat": 32.4116353,
    "lon": -88.70752979999999,
    "website": "http://www.ak193.org"
  },
  {
    "slug": "atchafalaya",
    "name": "Atchafalaya",
    "number": null,
    "council": "council:evangeline-area",
    "section": "G1",
    "region": "G",
    "hq_city": "Lafayette",
    "hq_state": "LA",
    "lat": 30.1877881,
    "lon": -92.0007929,
    "website": "https://www.eacscouting.org/oa"
  },
  {
    "slug": "atta-kulla-kulla",
    "name": "Atta Kulla Kulla",
    "number": null,
    "council": "council:blue-ridge",
    "section": "E7",
    "region": "E",
    "hq_city": "Greenville",
    "hq_state": "SC",
    "lat": 34.8018957,
    "lon": -82.2824942,
    "website": "http://akk185.org"
  },
  {
    "slug": "bigfoot",
    "name": "Bigfoot",
    "number": null,
    "council": "council:glaciers-edge",
    "section": "G9",
    "region": "G",
    "hq_city": "Madison",
    "hq_state": "WI",
    "lat": 43.0721661,
    "lon": -89.4007501,
    "website": "http://bigfoot620.org"
  },
  {
    "slug": "black-eagle",
    "name": "Black Eagle",
    "number": null,
    "council": "council:transatlantic",
    "section": "E17",
    "region": "E",
    "hq_city": "APO",
    "hq_state": "AE",
    "lat": 50.8633682,
    "lon": 4.4323362,
    "website": "https://tacscouting.org/activities/oa"
  },
  {
    "slug": "black-hawk",
    "name": "Black Hawk",
    "number": null,
    "council": "council:mississippi-valley",
    "section": "G7",
    "region": "G",
    "hq_city": "Quincy",
    "hq_state": "IL",
    "lat": 39.9377159,
    "lon": -91.3780489,
    "website": "http://blackhawklodgeoa.org"
  },
  {
    "slug": "blue-heron",
    "name": "Blue Heron",
    "number": null,
    "council": "council:tidewater",
    "section": "E9",
    "region": "E",
    "hq_city": "Virginia Beach",
    "hq_state": "VA",
    "lat": 36.8713405,
    "lon": -76.16587659999999,
    "website": "https://www.blueheronlodge.org"
  },
  {
    "slug": "blue-ox",
    "name": "Blue Ox",
    "number": null,
    "council": "council:gamehaven",
    "section": "G10",
    "region": "G",
    "hq_city": "Rochester",
    "hq_state": "MN",
    "lat": 44.050329,
    "lon": -92.45482799999999,
    "website": "https://gamehavenbsa.org/resources/for-scouts/oa"
  },
  {
    "slug": "bob-white",
    "name": "Bob White",
    "number": null,
    "council": "council:georgia-carolina",
    "section": "E7",
    "region": "E",
    "hq_city": "Augusta",
    "hq_state": "GA",
    "lat": 33.4547567,
    "lon": -82.1178577,
    "website": "https://www.bobwhitelodge87.org"
  },
  {
    "slug": "buckskin",
    "name": "Buckskin",
    "number": null,
    "council": "council:theodore-roosevelt",
    "section": "E18",
    "region": "E",
    "hq_city": "Massapequa",
    "hq_state": "NY",
    "lat": 40.6807088,
    "lon": -73.4690777,
    "website": "https://oa-buckskin412.weebly.com"
  },
  {
    "slug": "buffalo-mountain",
    "name": "Buffalo Mountain",
    "number": null,
    "council": "council:pathway-to-the-rockies",
    "section": "G12S",
    "region": "G",
    "hq_city": "Colorado Springs",
    "hq_state": "CO",
    "lat": 38.9012334,
    "lon": -104.8528796,
    "website": "http://buffalomountain.org"
  },
  {
    "slug": "caddo",
    "name": "Caddo",
    "number": null,
    "council": "council:norwela",
    "section": "G3",
    "region": "G",
    "hq_city": "Shreveport",
    "hq_state": "LA",
    "lat": 32.4784288,
    "lon": -93.72823029999999,
    "website": "http://www.caddolodge149.com"
  },
  {
    "slug": "cahuilla",
    "name": "Cahuilla",
    "number": null,
    "council": "council:california-inland-empire",
    "section": "G18S",
    "region": "G",
    "hq_city": "Redlands",
    "hq_state": "CA",
    "lat": 34.0554025,
    "lon": -117.1854935,
    "website": "http://www.snakepower.org"
  },
  {
    "slug": "catamount",
    "name": "Catamount",
    "number": null,
    "council": "council:heart-of-new-england",
    "section": "E19",
    "region": "E",
    "hq_city": "Rutland",
    "hq_state": "MA",
    "lat": 42.3717748,
    "lon": -71.97569899999999,
    "website": "http://www.OACatamount.org"
  },
  {
    "slug": "catawba",
    "name": "Catawba",
    "number": null,
    "council": "council:mecklenburg-county",
    "section": "E7",
    "region": "E",
    "hq_city": "Charlotte",
    "hq_state": "NC",
    "lat": 35.2179404,
    "lon": -80.82575729999999,
    "website": "http://www.catawba459.org"
  },
  {
    "slug": "chattahoochee",
    "name": "Chattahoochee",
    "number": null,
    "council": "council:chattahoochee",
    "section": "E6",
    "region": "E",
    "hq_city": "Columbus",
    "hq_state": "GA",
    "lat": 32.4700198,
    "lon": -84.99207369999999,
    "website": "http://www.chattahoocheelodge.com"
  },
  {
    "slug": "chilantakoba",
    "name": "Chilantakoba",
    "number": null,
    "council": "council:southeast-louisiana",
    "section": "G1",
    "region": "G",
    "hq_city": "Metairie",
    "hq_state": "LA",
    "lat": 29.9979133,
    "lon": -90.1718081,
    "website": "http://www.chilantakoba.com"
  },
  {
    "slug": "cho-gun-mun-a-nock",
    "name": "Cho-Gun-Mun-A-Nock",
    "number": null,
    "council": "council:hawkeye-area",
    "section": "G8",
    "region": "G",
    "hq_city": "Cedar Rapids",
    "hq_state": "IA",
    "lat": 41.9459228,
    "lon": -91.6778413,
    "website": "http://oalodge467.org"
  },
  {
    "slug": "chumash",
    "name": "Chumash",
    "number": null,
    "council": "council:los-padres",
    "section": "G18N",
    "region": "G",
    "hq_city": "Santa Barbara",
    "hq_state": "CA",
    "lat": 34.4370297,
    "lon": -119.7547204,
    "website": "http://www.chumashlodge90.net"
  },
  {
    "slug": "colonneh",
    "name": "Colonneh",
    "number": null,
    "council": "council:sam-houston-area",
    "section": "G2",
    "region": "G",
    "hq_city": "Houston",
    "hq_state": "TX",
    "lat": 29.8096615,
    "lon": -95.43817659999999,
    "website": "https://shacbsa.org/order-of-the-arrow"
  },
  {
    "slug": "comanche",
    "name": "Comanche",
    "number": null,
    "council": "council:louisiana-purchase",
    "section": "G1",
    "region": "G",
    "hq_city": "Monroe",
    "hq_state": "LA",
    "lat": 32.5380532,
    "lon": -92.10695790000001,
    "website": "https://www.louisianapurchasecouncil.org/oa"
  },
  {
    "slug": "coosa",
    "name": "Coosa",
    "number": null,
    "council": "council:greater-alabama",
    "section": "E6",
    "region": "E",
    "hq_city": "Birmingham",
    "hq_state": "AL",
    "lat": 33.4812308,
    "lon": -86.70678889999999,
    "website": "http://www.coosa50.squarespace.com"
  },
  {
    "slug": "cowikee",
    "name": "Cowikee",
    "number": null,
    "council": "council:alabama-florida",
    "section": "E4",
    "region": "E",
    "hq_city": "Dothan",
    "hq_state": "AL",
    "lat": 31.2394261,
    "lon": -85.49895409999999,
    "website": "http://www.cowikee.org"
  },
  {
    "slug": "crazy-horse",
    "name": "Crazy Horse",
    "number": null,
    "council": "council:black-hills-area",
    "section": "G12N",
    "region": "G",
    "hq_city": "Rapid City",
    "hq_state": "SD",
    "lat": 44.0886574,
    "lon": -103.2164962,
    "website": null
  },
  {
    "slug": "croatan",
    "name": "Croatan",
    "number": null,
    "council": "council:east-carolina",
    "section": "E8",
    "region": "E",
    "hq_city": "Kinston",
    "hq_state": "NC",
    "lat": 35.26,
    "lon": -77.58,
    "website": "http://www.croatan.org"
  },
  {
    "slug": "dzie-hauk-tonga",
    "name": "Dzie-Hauk Tonga",
    "number": null,
    "council": "council:jayhawk-area",
    "section": "G6",
    "region": "G",
    "hq_city": "Topeka",
    "hq_state": "KS",
    "lat": 39.0439654,
    "lon": -95.6729178,
    "website": "https://dziehauktonga.org"
  },
  {
    "slug": "echeconnee",
    "name": "Echeconnee",
    "number": null,
    "council": "council:central-georgia",
    "section": "E6",
    "region": "E",
    "hq_city": "Macon",
    "hq_state": "GA",
    "lat": 32.8036776,
    "lon": -83.5734386,
    "website": "http://www.echeconnee.org"
  },
  {
    "slug": "echockotee",
    "name": "Echockotee",
    "number": null,
    "council": "council:north-florida",
    "section": "E5",
    "region": "E",
    "hq_city": "Jacksonville",
    "hq_state": "FL",
    "lat": 30.3177627,
    "lon": -81.7239147,
    "website": "http://www.echockotee.org"
  },
  {
    "slug": "egwa-tawa-dee",
    "name": "Egwa Tawa Dee",
    "number": null,
    "council": "council:atlanta-area",
    "section": "E6",
    "region": "E",
    "hq_city": "Atlanta",
    "hq_state": "GA",
    "lat": 33.8933661,
    "lon": -84.4650446,
    "website": "https://aacegwa.org"
  },
  {
    "slug": "erielhonan",
    "name": "Erielhonan",
    "number": null,
    "council": "council:lake-erie",
    "section": "E13",
    "region": "E",
    "hq_city": "Cleveland",
    "hq_state": "OH",
    "lat": 41.49314589999999,
    "lon": -81.67434659999999,
    "website": "http://www.erielhonan.org"
  },
  {
    "slug": "es-kaielgu",
    "name": "Es-Kaielgu",
    "number": null,
    "council": "council:inland-northwest",
    "section": "G14",
    "region": "G",
    "hq_city": "Spokane",
    "hq_state": "WA",
    "lat": 47.6671731,
    "lon": -117.4176484,
    "website": "http://www.nwscouts.org/oa"
  },
  {
    "slug": "eswau-huppeday",
    "name": "Eswau Huppeday",
    "number": null,
    "council": "council:piedmont-420",
    "section": "E7",
    "region": "E",
    "hq_city": "Gastonia",
    "hq_state": "NC",
    "lat": 35.2637147,
    "lon": -81.185756,
    "website": "http://eswau.net"
  },
  {
    "slug": "eternal-flame",
    "name": "Eternal Flame",
    "number": null,
    "council": "council:great-falls",
    "section": "E15",
    "region": "E",
    "hq_city": "Buffalo",
    "hq_state": "NY",
    "lat": 42.9240223,
    "lon": -78.77880669999999,
    "website": "http://www.gfcscouting.org/programs/order-of-the-arrow"
  },
  {
    "slug": "golden-sun",
    "name": "Golden Sun",
    "number": null,
    "council": "council:cornhusker",
    "section": "G5",
    "region": "G",
    "hq_city": "Walton",
    "hq_state": "NE",
    "lat": 40.7986111,
    "lon": -96.56195679999999,
    "website": "https://www.goldensunlodge.org"
  },
  {
    "slug": "gyantwachia",
    "name": "Gyantwachia",
    "number": null,
    "council": "council:chief-cornplanter",
    "section": "E21",
    "region": "E",
    "hq_city": "Warren",
    "hq_state": "PA",
    "lat": 41.8478711,
    "lon": -79.14989249999999,
    "website": "http://www.oa255.com"
  },
  {
    "slug": "hasinai",
    "name": "Hasinai",
    "number": null,
    "council": "council:three-rivers",
    "section": "G2",
    "region": "G",
    "hq_city": "Beaumont",
    "hq_state": "TX",
    "lat": 30.0436753,
    "lon": -94.1323857,
    "website": "http://www.3riversbsa.org"
  },
  {
    "slug": "ho-nan-ne-ho-ont",
    "name": "Ho-Nan-Ne-Ho-Ont",
    "number": null,
    "council": "council:allegheny-highlands",
    "section": "E21",
    "region": "E",
    "hq_city": "Falconer",
    "hq_state": "NY",
    "lat": 42.127288,
    "lon": -79.2076191,
    "website": "https://www.ahcoa165.org"
  },
  {
    "slug": "hungteetsepoppi",
    "name": "Hungteetsepoppi",
    "number": null,
    "council": "council:piedmont",
    "section": "G17S",
    "region": "G",
    "hq_city": "Piedmont",
    "hq_state": "CA",
    "lat": 37.825132,
    "lon": -122.2317306,
    "website": "http://oa466.org"
  },
  {
    "slug": "i-tsu-la",
    "name": "I-Tsu-La",
    "number": null,
    "council": "council:coastal-georgia",
    "section": "E6",
    "region": "E",
    "hq_city": "Savannah",
    "hq_state": "GA",
    "lat": 31.9840091,
    "lon": -81.15763439999999,
    "website": "https://coastalgeorgiabsa.org"
  },
  {
    "slug": "illinek",
    "name": "Illinek",
    "number": null,
    "council": "council:abraham-lincoln",
    "section": "G7",
    "region": "G",
    "hq_city": "Springfield",
    "hq_state": "IL",
    "lat": 39.7266352,
    "lon": -89.6432524,
    "website": "http://illineklodge.org"
  },
  {
    "slug": "illini",
    "name": "Illini",
    "number": null,
    "council": "council:prairielands",
    "section": "G7",
    "region": "G",
    "hq_city": "Champaign",
    "hq_state": "IL",
    "lat": 40.156107,
    "lon": -88.2683314,
    "website": "http://www.illinilodge55.com"
  },
  {
    "slug": "ini-to",
    "name": "Ini-To",
    "number": null,
    "council": "council:flint-river",
    "section": "E6",
    "region": "E",
    "hq_city": "Griffin",
    "hq_state": "GA",
    "lat": 33.2136919,
    "lon": -84.28190510000002,
    "website": "http://www.flintrivercouncil.org"
  },
  {
    "slug": "itibapishe-iti-hollo",
    "name": "Itibapishe Iti Hollo",
    "number": null,
    "council": "council:central-north-carolina",
    "section": "E7",
    "region": "E",
    "hq_city": "Albemarle",
    "hq_state": "NC",
    "lat": 35.3320514,
    "lon": -80.2335598,
    "website": "http://www.itibap188.org"
  },
  {
    "slug": "ittawamba",
    "name": "Ittawamba",
    "number": null,
    "council": "council:west-tennessee-area",
    "section": "E3",
    "region": "E",
    "hq_city": "Jackson",
    "hq_state": "TN",
    "lat": 35.6501179,
    "lon": -88.8647316,
    "website": "https://www.ittawamba.org"
  },
  {
    "slug": "jaccos-towne",
    "name": "Jaccos Towne",
    "number": null,
    "council": "council:crossroads-of-america",
    "section": "E1",
    "region": "E",
    "hq_city": "Indianapolis",
    "hq_state": "IN",
    "lat": 39.8685099,
    "lon": -86.04288489999999,
    "website": "http://www.jaccostownelodge.org"
  },
  {
    "slug": "japeechen",
    "name": "Japeechen",
    "number": null,
    "council": "council:jersey-shore",
    "section": "E17",
    "region": "E",
    "hq_city": "Toms River",
    "hq_state": "NJ",
    "lat": 40.0001151,
    "lon": -74.2297382,
    "website": "http://www.jerseyshorescouts.org/oa"
  },
  {
    "slug": "kansa",
    "name": "Kansa",
    "number": null,
    "council": "council:quivira",
    "section": "G5",
    "region": "G",
    "hq_city": "Wichita",
    "hq_state": "KS",
    "lat": 37.7417383,
    "lon": -97.2842515,
    "website": "http://www.kansalodge.org"
  },
  {
    "slug": "kanwa-tho",
    "name": "Kanwa Tho",
    "number": null,
    "council": "council:three-harbors",
    "section": "G9",
    "region": "G",
    "hq_city": "Milwaukee",
    "hq_state": "WI",
    "lat": 43.02810909999999,
    "lon": -88.01675159999999,
    "website": "http://www.kanwatho.org"
  },
  {
    "slug": "karankawa",
    "name": "Karankawa",
    "number": null,
    "council": "council:south-texas",
    "section": "G2",
    "region": "G",
    "hq_city": "Corpus Christi",
    "hq_state": "TX",
    "lat": 27.727576,
    "lon": -97.37698300000001,
    "website": "https://www.southtexasscouting.org/order-of-the-ar"
  },
  {
    "slug": "kawida",
    "name": "Kawida",
    "number": null,
    "council": "council:blue-grass",
    "section": "E3",
    "region": "E",
    "hq_city": "Lexington",
    "hq_state": "KY",
    "lat": 38.0093979,
    "lon": -84.51665009999999,
    "website": "https://www.kawida.org"
  },
  {
    "slug": "kidi-kidish",
    "name": "Kidi Kidish",
    "number": null,
    "council": "council:coronado-area",
    "section": "G5",
    "region": "G",
    "hq_city": "Salina",
    "hq_state": "KS",
    "lat": 38.842906,
    "lon": -97.60778549999999,
    "website": "https://www.coronadoscout.org"
  },
  {
    "slug": "kintecoying",
    "name": "Kintecoying",
    "number": null,
    "council": "council:greater-new-york",
    "section": "E18",
    "region": "E",
    "hq_city": "New York",
    "hq_state": "NY",
    "lat": 40.7599579,
    "lon": -73.9685442,
    "website": "https://nycscouting.org/lodge"
  },
  {
    "slug": "kiondaga",
    "name": "Kiondaga",
    "number": null,
    "council": "council:buffalo-trace",
    "section": "E1",
    "region": "E",
    "hq_city": "Evansville",
    "hq_state": "IN",
    "lat": 37.9759085,
    "lon": -87.5072497,
    "website": null
  },
  {
    "slug": "kiskakon",
    "name": "Kiskakon",
    "number": null,
    "council": "council:anthony-wayne-area",
    "section": "E1",
    "region": "E",
    "hq_city": "Fort Wayne",
    "hq_state": "IN",
    "lat": 41.0287304,
    "lon": -85.2512488,
    "website": "http://www.awac.org/order-of-the-arrow"
  },
  {
    "slug": "kittan",
    "name": "Kittan",
    "number": null,
    "council": "council:twin-rivers",
    "section": "E20",
    "region": "E",
    "hq_city": "Albany",
    "hq_state": "NY",
    "lat": 42.7047381,
    "lon": -73.8566405,
    "website": "http://www.kittanlodge.org"
  },
  {
    "slug": "kittatinny",
    "name": "Kittatinny",
    "number": null,
    "council": "council:hawk-mountain",
    "section": "E11",
    "region": "E",
    "hq_city": "Reading",
    "hq_state": "PA",
    "lat": 40.4145866,
    "lon": -75.9384986,
    "website": "https://kittatinny5.org"
  },
  {
    "slug": "klahican",
    "name": "Klahican",
    "number": null,
    "council": "council:cape-fear",
    "section": "E8",
    "region": "E",
    "hq_city": "Wilmington",
    "hq_state": "NC",
    "lat": 34.24,
    "lon": -77.95,
    "website": "http://www.klahican.org"
  },
  {
    "slug": "kola",
    "name": "Kola",
    "number": null,
    "council": "council:adventure-west",
    "section": "G12N",
    "region": "G",
    "hq_city": "Greeley",
    "hq_state": "CO",
    "lat": 40.4024278,
    "lon": -104.7162752,
    "website": "https://awbsa.org/oa-kola-lodge"
  },
  {
    "slug": "kon-wapos",
    "name": "Kon Wapos",
    "number": null,
    "council": "council:bay-lakes",
    "section": "G10",
    "region": "G",
    "hq_city": "Appleton",
    "hq_state": "WI",
    "lat": 44.2417993,
    "lon": -88.4642429,
    "website": "http://www.konwapos.org"
  },
  {
    "slug": "konepaka-ketiwa",
    "name": "Konepaka Ketiwa",
    "number": null,
    "council": "council:illowa",
    "section": "G8",
    "region": "G",
    "hq_city": "Davenport",
    "hq_state": "IA",
    "lat": 41.5656372,
    "lon": -90.568258,
    "website": "https://illowabsa.org/order-of-the-arrow"
  },
  {
    "slug": "ku-ni-eh",
    "name": "Ku-Ni-Eh",
    "number": null,
    "council": "council:dan-beard",
    "section": "E2",
    "region": "E",
    "hq_city": "Cincinnati",
    "hq_state": "OH",
    "lat": 39.2458751,
    "lon": -84.425765,
    "website": "http://www.ku-ni-eh.org"
  },
  {
    "slug": "kunamokst",
    "name": "Kunamokst",
    "number": null,
    "council": "council:pacific-crest",
    "section": "G16",
    "region": "G",
    "hq_city": "Eugene",
    "hq_state": "OR",
    "lat": 44.0606234,
    "lon": -123.0714236,
    "website": "https://kunamokst.org"
  },
  {
    "slug": "kuskitannee",
    "name": "Kuskitannee",
    "number": null,
    "council": "council:moraine-trails",
    "section": "E21",
    "region": "E",
    "hq_city": "Butler",
    "hq_state": "PA",
    "lat": 40.8449608,
    "lon": -79.88238079999999,
    "website": "http://www.kuskitannee.org"
  },
  {
    "slug": "kwahadi",
    "name": "Kwahadi",
    "number": null,
    "council": "council:conquistador",
    "section": "G13E",
    "region": "G",
    "hq_city": "Roswell",
    "hq_state": "NM",
    "lat": 33.4255576,
    "lon": -104.5538591,
    "website": "http://www.nmscouts.org"
  },
  {
    "slug": "langundowi",
    "name": "Langundowi",
    "number": null,
    "council": "council:french-creek",
    "section": "E21",
    "region": "E",
    "hq_city": "Erie",
    "hq_state": "PA",
    "lat": 42.0453254,
    "lon": -80.0712813,
    "website": null
  },
  {
    "slug": "lenape",
    "name": "Lenape",
    "number": null,
    "council": "council:garden-state",
    "section": "E17",
    "region": "E",
    "hq_city": "Westampton",
    "hq_state": "NJ",
    "lat": 40.0092421,
    "lon": -74.837851,
    "website": "http://www.lenape8.org"
  },
  {
    "slug": "lenapehoking",
    "name": "Lenapehoking",
    "number": null,
    "council": "council:northern-new-jersey",
    "section": "E17",
    "region": "E",
    "hq_city": "Oakland",
    "hq_state": "NJ",
    "lat": 41.01377770000001,
    "lon": -74.2647708,
    "website": "http://www.nnjbsa.org/oa"
  },
  {
    "slug": "lowaneu-allanque",
    "name": "Lowaneu Allanque",
    "number": null,
    "council": "council:three-fires",
    "section": "G9",
    "region": "G",
    "hq_city": "St. Charles",
    "hq_state": "IL",
    "lat": 41.9178371,
    "lon": -88.3196889,
    "website": "http://www.oa41.org"
  },
  {
    "slug": "lowanne-nimat",
    "name": "Lowanne Nimat",
    "number": null,
    "council": "council:longhouse",
    "section": "E15",
    "region": "E",
    "hq_city": "Syracuse",
    "hq_state": "NY",
    "lat": 43.1071429,
    "lon": -76.1486644,
    "website": "http://cnyscouts.org/oa"
  },
  {
    "slug": "lowwapaneu",
    "name": "Lowwapaneu",
    "number": null,
    "council": "council:northeastern-pennsylvania",
    "section": "E17",
    "region": "E",
    "hq_city": "Moosic",
    "hq_state": "PA",
    "lat": 41.3688103,
    "lon": -75.6881129,
    "website": "http://www.lowwapaneu.org"
  },
  {
    "slug": "ma-ka-ja-wan",
    "name": "Ma-Ka-Ja-Wan",
    "number": null,
    "council": "council:northeast-illinois",
    "section": "G9",
    "region": "G",
    "hq_city": "Vernon Hills",
    "hq_state": "IL",
    "lat": 42.2102172,
    "lon": -87.9449569,
    "website": "https://oalodge40.blogspot.com"
  },
  {
    "slug": "madockawanda",
    "name": "Madockawanda",
    "number": null,
    "council": "council:pine-tree",
    "section": "E19",
    "region": "E",
    "hq_city": "Raymond",
    "hq_state": "ME",
    "lat": 43.9496793,
    "lon": -70.469051,
    "website": "http://www.madockawanda.org"
  },
  {
    "slug": "mahicantuck",
    "name": "Mahicantuck",
    "number": null,
    "council": "council:greater-hudson-valley",
    "section": "E18",
    "region": "E",
    "hq_city": "Mohegan Lake",
    "hq_state": "NY",
    "lat": 41.31085050000001,
    "lon": -73.8477874,
    "website": "https://www.ghvscouting.org/mahicantuck"
  },
  {
    "slug": "malibu",
    "name": "Malibu",
    "number": null,
    "council": "council:western-los-angeles-county",
    "section": "G18N",
    "region": "G",
    "hq_city": "Van Nuys",
    "hq_state": "CA",
    "lat": 34.2019516,
    "lon": -118.4936393,
    "website": "https://malibulodge.scouting-la.org"
  },
  {
    "slug": "marnoc",
    "name": "Marnoc",
    "number": null,
    "council": "council:great-trail",
    "section": "E13",
    "region": "E",
    "hq_city": "Stow",
    "hq_state": "OH",
    "lat": 41.1893568,
    "lon": -81.46568359999999,
    "website": "http://www.marnoc.org"
  },
  {
    "slug": "mawat-woakus",
    "name": "Mawat Woakus",
    "number": null,
    "council": "council:black-swamp-area",
    "section": "E2",
    "region": "E",
    "hq_city": "Findlay",
    "hq_state": "OH",
    "lat": 41.0648688,
    "lon": -83.6647804,
    "website": "http://www.mawatwoakus.org"
  },
  {
    "slug": "miami",
    "name": "Miami",
    "number": null,
    "council": "council:miami-valley",
    "section": "E2",
    "region": "E",
    "hq_city": "Dayton",
    "hq_state": "OH",
    "lat": 39.8529073,
    "lon": -84.1888235,
    "website": "http://www.miami495.org"
  },
  {
    "slug": "mikanakawa",
    "name": "Mikanakawa",
    "number": null,
    "council": "council:circle-ten",
    "section": "G3",
    "region": "G",
    "hq_city": "Dallas",
    "hq_state": "TX",
    "lat": 32.8376904,
    "lon": -96.8670224,
    "website": "http://www.miki.org"
  },
  {
    "slug": "mishigami",
    "name": "Mishigami",
    "number": null,
    "council": "council:michigan-crossroads",
    "section": "E2",
    "region": "E",
    "hq_city": "Eagle",
    "hq_state": "MI",
    "lat": 42.8105761,
    "lon": -84.79021999999999,
    "website": "https://mishigami.org"
  },
  {
    "slug": "mitigwa",
    "name": "Mitigwa",
    "number": null,
    "council": "council:mid-iowa",
    "section": "G6",
    "region": "G",
    "hq_city": "Des Moines",
    "hq_state": "IA",
    "lat": 41.5457743,
    "lon": -93.7010009,
    "website": "http://www.mitigwa-lodge.org"
  },
  {
    "slug": "mixti-wanaxe",
    "name": "Mixti Wanaxe",
    "number": null,
    "council": "council:natural-state",
    "section": "G4",
    "region": "G",
    "hq_city": "Little Rock",
    "hq_state": "AR",
    "lat": 34.7626589,
    "lon": -92.310867,
    "website": "http://mixti-wanaxe.org"
  },
  {
    "slug": "monaken",
    "name": "Monaken",
    "number": null,
    "council": "council:juniata-valley",
    "section": "E21",
    "region": "E",
    "hq_city": "Reedsville",
    "hq_state": "PA",
    "lat": 40.68618319999999,
    "lon": -77.5976807,
    "website": "http://www.monaken.org"
  },
  {
    "slug": "mowogo",
    "name": "Mowogo",
    "number": null,
    "council": "council:northeast-georgia",
    "section": "E6",
    "region": "E",
    "hq_city": "Jefferson",
    "hq_state": "GA",
    "lat": 34.1170537,
    "lon": -83.5723876,
    "website": "http://www.mowogo.org"
  },
  {
    "slug": "muscogee",
    "name": "Muscogee",
    "number": null,
    "council": "council:indian-waters",
    "section": "E7",
    "region": "E",
    "hq_city": "Columbia",
    "hq_state": "SC",
    "lat": 34.01761010000001,
    "lon": -81.0868672,
    "website": "http://muscogeelodge.org"
  },
  {
    "slug": "na-mokupuni-o-lawelawe",
    "name": "Na Mokupuni O Lawelawe",
    "number": null,
    "council": "council:aloha",
    "section": "G19",
    "region": "G",
    "hq_city": "Honolulu",
    "hq_state": "HI",
    "lat": 21.3362246,
    "lon": -157.8373207,
    "website": "https://oalodge567.org"
  },
  {
    "slug": "na-tsi-hi",
    "name": "Na Tsi Hi",
    "number": null,
    "council": "council:monmouth",
    "section": "E17",
    "region": "E",
    "hq_city": "Morganville",
    "hq_state": "NJ",
    "lat": 40.3518564,
    "lon": -74.29303170000001,
    "website": "http://www.NaTsiHi.org"
  },
  {
    "slug": "naguonabe",
    "name": "Naguonabe",
    "number": null,
    "council": "council:central-minnesota",
    "section": "G11",
    "region": "G",
    "hq_city": "Sartell",
    "hq_state": "MN",
    "lat": 45.5919436,
    "lon": -94.22481979999999,
    "website": "http://www.bsacmc.org/#!order-of-the-arrow/c1ypz"
  },
  {
    "slug": "nakona",
    "name": "Nakona",
    "number": null,
    "council": "council:south-plains",
    "section": "G3",
    "region": "G",
    "hq_city": "Lubbock",
    "hq_state": "TX",
    "lat": 33.5431294,
    "lon": -101.8511198,
    "website": "http://www.nakona150.org"
  },
  {
    "slug": "nampa-tsi",
    "name": "Nampa-Tsi",
    "number": null,
    "council": "council:great-rivers",
    "section": "G6",
    "region": "G",
    "hq_city": "Columbia",
    "hq_state": "MO",
    "lat": 38.9702395,
    "lon": -92.4259082,
    "website": "http://www.nampa-tsi.org"
  },
  {
    "slug": "nanuk",
    "name": "Nanuk",
    "number": null,
    "council": "council:great-alaska",
    "section": "G15",
    "region": "G",
    "hq_city": "Anchorage",
    "hq_state": "AK",
    "lat": 61.19225,
    "lon": -149.7470387,
    "website": "http://www.scoutingalaska.org/OA"
  },
  {
    "slug": "nawakwa",
    "name": "Nawakwa",
    "number": null,
    "council": "council:heart-of-virginia",
    "section": "E9",
    "region": "E",
    "hq_city": "Henrico",
    "hq_state": "VA",
    "lat": 37.6335677,
    "lon": -77.4661189,
    "website": "http://www.nawakwa.org"
  },
  {
    "slug": "nayawin-rar",
    "name": "Nayawin Rar",
    "number": null,
    "council": "council:tuscarora",
    "section": "E8",
    "region": "E",
    "hq_city": "Goldsboro",
    "hq_state": "NC",
    "lat": 35.4286135,
    "lon": -78.0627812,
    "website": "https://www.tuscarorabsa.org/nrl"
  },
  {
    "slug": "nebagamon",
    "name": "Nebagamon",
    "number": null,
    "council": "council:las-vegas-area",
    "section": "G13W",
    "region": "G",
    "hq_city": "Las Vegas",
    "hq_state": "NV",
    "lat": 36.0587032,
    "lon": -115.1392501,
    "website": "http://www.Nebagamon.org"
  },
  {
    "slug": "nentego",
    "name": "Nentego",
    "number": null,
    "council": "council:del-mar-va",
    "section": "E10",
    "region": "E",
    "hq_city": "Dover",
    "hq_state": "DE",
    "lat": 39.1265112,
    "lon": -75.54069969999999,
    "website": "http://www.delmarvacouncil.org/order-of-the-arrow"
  },
  {
    "slug": "nentico",
    "name": "Nentico",
    "number": null,
    "council": "council:baltimore-area",
    "section": "E10",
    "region": "E",
    "hq_city": "Baltimore",
    "hq_state": "MD",
    "lat": 39.3213916,
    "lon": -76.6280061,
    "website": "http://www.nentico.org"
  },
  {
    "slug": "netawatwees",
    "name": "Netawatwees",
    "number": null,
    "council": "council:muskingum-valley",
    "section": "E13",
    "region": "E",
    "hq_city": "Zanesville",
    "hq_state": "OH",
    "lat": 39.9482995,
    "lon": -82.014624,
    "website": "http://netawatwees424.org"
  },
  {
    "slug": "netopalis-sipo-schipinachk",
    "name": "Netopalis Sipo Schipinachk",
    "number": null,
    "council": "council:longhorn",
    "section": "G3",
    "region": "G",
    "hq_city": "Hurst",
    "hq_state": "TX",
    "lat": 32.8591337,
    "lon": -97.17633219999999,
    "website": "https://www.netopalis.org"
  },
  {
    "slug": "new-frontier",
    "name": "New Frontier",
    "number": null,
    "council": "council:high-desert",
    "section": "G13E",
    "region": "G",
    "hq_city": "Albuquerque",
    "hq_state": "NM",
    "lat": 35.1470902,
    "lon": -106.6016198,
    "website": "https://www.scoutingamericahighdesertcouncil.org"
  },
  {
    "slug": "nguttitehen",
    "name": "Nguttitehen",
    "number": null,
    "council": "council:lincoln-heritage",
    "section": "E3",
    "region": "E",
    "hq_city": "Louisville",
    "hq_state": "KY",
    "lat": 38.2178527,
    "lon": -85.52736589999999,
    "website": "http://www.nguttitehen.org"
  },
  {
    "slug": "ni-sanak-tani",
    "name": "Ni-Sanak-Tani",
    "number": null,
    "council": "council:gateway-area",
    "section": "G10",
    "region": "G",
    "hq_city": "La Crosse",
    "hq_state": "WI",
    "lat": 43.8213288,
    "lon": -91.217118,
    "website": null
  },
  {
    "slug": "nischa-achowalogen",
    "name": "Nischa Achowalogen",
    "number": null,
    "council": "council:golden-spread",
    "section": "G3",
    "region": "G",
    "hq_city": "Amarillo",
    "hq_state": "TX",
    "lat": 35.2141123,
    "lon": -101.9067636,
    "website": "https://rb.gy/lenaj"
  },
  {
    "slug": "nischa-chuppecat",
    "name": "Nischa Chuppecat",
    "number": null,
    "council": "council:hoosier-trails",
    "section": "E1",
    "region": "E",
    "hq_city": "Bloomington",
    "hq_state": "IN",
    "lat": 39.173482,
    "lon": -86.5033508,
    "website": "https://hoosiertrails.org/programs/#oa"
  },
  {
    "slug": "nisha-kittan",
    "name": "Nisha Kittan",
    "number": null,
    "council": "council:greater-saint-louis-area",
    "section": "G7",
    "region": "G",
    "hq_city": "Chesterfield",
    "hq_state": "MO",
    "lat": 38.6291495,
    "lon": -90.5184984,
    "website": "https://nklodge.org"
  },
  {
    "slug": "nisqually",
    "name": "Nisqually",
    "number": null,
    "council": "council:pacific-harbors",
    "section": "G15",
    "region": "G",
    "hq_city": "Tacoma",
    "hq_state": "WA",
    "lat": 47.2420353,
    "lon": -122.5019129,
    "website": "http://www.nisqually155.org"
  },
  {
    "slug": "o-ni-flo",
    "name": "O-Ni-Flo",
    "number": null,
    "council": "council:pony-express",
    "section": "G5",
    "region": "G",
    "hq_city": "St. Joseph",
    "hq_state": "MO",
    "lat": 39.7827501,
    "lon": -94.7931516,
    "website": "http://ponyexpressbsa.org"
  },
  {
    "slug": "o-shot-caw",
    "name": "O-Shot-Caw",
    "number": null,
    "council": "council:south-florida",
    "section": "E5",
    "region": "E",
    "hq_city": "Davie",
    "hq_state": "FL",
    "lat": 26.0791853,
    "lon": -80.3388043,
    "website": "https://O-Shot-Caw.org"
  },
  {
    "slug": "occoneechee",
    "name": "Occoneechee",
    "number": null,
    "council": "council:occoneechee",
    "section": "E8",
    "region": "E",
    "hq_city": "Raleigh",
    "hq_state": "NC",
    "lat": 35.8252695,
    "lon": -78.6074766,
    "website": "https://lodge104.net"
  },
  {
    "slug": "oconomowoc",
    "name": "Oconomowoc",
    "number": null,
    "council": "council:mountaineer-area",
    "section": "E13",
    "region": "E",
    "hq_city": "Fairmont",
    "hq_state": "WV",
    "lat": 39.4900103,
    "lon": -80.10682969999999,
    "website": "https://mountaineerscouting.org/oa"
  },
  {
    "slug": "octoraro",
    "name": "Octoraro",
    "number": null,
    "council": "council:chester-county",
    "section": "E11",
    "region": "E",
    "hq_city": "Exton",
    "hq_state": "PA",
    "lat": 40.0254739,
    "lon": -75.6392353,
    "website": "http://www.octoraro22.org"
  },
  {
    "slug": "ofi-tohbi",
    "name": "Ofi' Tohbi",
    "number": null,
    "council": "council:natchez-trace",
    "section": "E3",
    "region": "E",
    "hq_city": "Tupelo",
    "hq_state": "MS",
    "lat": 34.2635001,
    "lon": -88.7582584,
    "website": "http://www.ofitohbi.org"
  },
  {
    "slug": "ohkwaliha-ka",
    "name": "Ohkwaliha-Ka",
    "number": null,
    "council": "council:leatherstocking",
    "section": "E15",
    "region": "E",
    "hq_city": "Utica",
    "hq_state": "NY",
    "lat": 43.0948255,
    "lon": -75.24397619999999,
    "website": "http://www.oalodge34.org/wp2"
  },
  {
    "slug": "ohlone",
    "name": "Ohlone",
    "number": null,
    "council": "council:pacific-skyline",
    "section": "G17S",
    "region": "G",
    "hq_city": "Foster City",
    "hq_state": "CA",
    "lat": 37.5671945,
    "lon": -122.2728424,
    "website": "http://www.ohlone63.org"
  },
  {
    "slug": "onerahtokha",
    "name": "Onerahtokha",
    "number": null,
    "council": "council:shenandoah-area",
    "section": "E9",
    "region": "E",
    "hq_city": "Winchester",
    "hq_state": "VA",
    "lat": 39.137928,
    "lon": -78.18496549999999,
    "website": "http://www.sacscouting.org/OA"
  },
  {
    "slug": "orca",
    "name": "Orca",
    "number": null,
    "council": "council:redwood-empire",
    "section": "G17N",
    "region": "G",
    "hq_city": "Santa Rosa",
    "hq_state": "CA",
    "lat": 38.4241531,
    "lon": -122.749796,
    "website": "https://orca194.org"
  },
  {
    "slug": "osceola",
    "name": "Osceola",
    "number": null,
    "council": "council:southwest-florida",
    "section": "E5",
    "region": "E",
    "hq_city": "Fort Myers",
    "hq_state": "FL",
    "lat": 26.5827528,
    "lon": -81.8763141,
    "website": "http://www.swflcouncilbsa.org/osceola-lodge-564/76461"
  },
  {
    "slug": "otahnagon",
    "name": "Otahnagon",
    "number": null,
    "council": "council:baden-powell",
    "section": "E15",
    "region": "E",
    "hq_city": "Binghamton",
    "hq_state": "NY",
    "lat": 42.2085214,
    "lon": -75.85088329999999,
    "website": "https://www.otahnagonlodge172.org"
  },
  {
    "slug": "otyokwa",
    "name": "Otyokwa",
    "number": null,
    "council": "council:chippewa-valley",
    "section": "G10",
    "region": "G",
    "hq_city": "Eau Claire",
    "hq_state": "WI",
    "lat": 44.8096405,
    "lon": -91.4725607,
    "website": "https://sites.google.com/view/otyokwalodge337/home"
  },
  {
    "slug": "owaneco",
    "name": "Owaneco",
    "number": null,
    "council": "council:connecticut-yankee",
    "section": "E20",
    "region": "E",
    "hq_city": "Milford",
    "hq_state": "CT",
    "lat": 41.2542338,
    "lon": -73.0737299,
    "website": "http://www.owaneco.org"
  },
  {
    "slug": "pa-hin",
    "name": "Pa-Hin",
    "number": null,
    "council": "council:northern-lights",
    "section": "G11",
    "region": "G",
    "hq_city": "Fargo",
    "hq_state": "ND",
    "lat": 46.8494013,
    "lon": -96.8520092,
    "website": "http://www.pahinlodge.org"
  },
  {
    "slug": "pamola",
    "name": "Pamola",
    "number": null,
    "council": "council:katahdin-area",
    "section": "E19",
    "region": "E",
    "hq_city": "Bangor",
    "hq_state": "ME",
    "lat": 44.8,
    "lon": -68.78,
    "website": "http://www.pamola.org"
  },
  {
    "slug": "papago",
    "name": "Papago",
    "number": null,
    "council": "council:catalina",
    "section": "G13W",
    "region": "G",
    "hq_city": "Tucson",
    "hq_state": "AZ",
    "lat": 32.2210985,
    "lon": -110.9382912,
    "website": "http://www.papagolodge.org"
  },
  {
    "slug": "passaconaway",
    "name": "Passaconaway",
    "number": null,
    "council": "council:daniel-webster",
    "section": "E19",
    "region": "E",
    "hq_city": "Manchester",
    "hq_state": "NH",
    "lat": 42.9487548,
    "lon": -71.3893208,
    "website": "https://oa.nhscouting.org"
  },
  {
    "slug": "paugassett",
    "name": "Paugassett",
    "number": null,
    "council": "council:housatonic",
    "section": "E20",
    "region": "E",
    "hq_city": "Derby",
    "hq_state": "CT",
    "lat": 41.3102926,
    "lon": -73.07548419999999,
    "website": null
  },
  {
    "slug": "pellissippi",
    "name": "Pellissippi",
    "number": null,
    "council": "council:great-smoky-mountain",
    "section": "E3",
    "region": "E",
    "hq_city": "Knoxville",
    "hq_state": "TN",
    "lat": 35.9490141,
    "lon": -84.0208569,
    "website": "http://www.easttnscouts.org/oa"
  },
  {
    "slug": "penateka",
    "name": "Penateka",
    "number": null,
    "council": "council:texas-trails",
    "section": "G3",
    "region": "G",
    "hq_city": "Abilene",
    "hq_state": "TX",
    "lat": 32.4539952,
    "lon": -99.73532739999999,
    "website": "http://www.texastrailsbsa.com/programs/order-of-the-arrow"
  },
  {
    "slug": "pennacook",
    "name": "Pennacook",
    "number": null,
    "council": "council:spirit-of-adventure",
    "section": "E19",
    "region": "E",
    "hq_city": "Milton",
    "hq_state": "MA",
    "lat": 42.2343115,
    "lon": -71.0913477,
    "website": "http://www.oapennacook.org"
  },
  {
    "slug": "pocumtuc",
    "name": "Pocumtuc",
    "number": null,
    "council": "council:western-massachusetts",
    "section": "E20",
    "region": "E",
    "hq_city": "Holyoke",
    "hq_state": "MA",
    "lat": 42.1969974,
    "lon": -72.6172863,
    "website": "http://www.wmascouting.org/oa"
  },
  {
    "slug": "prairie-thunder",
    "name": "Prairie Thunder",
    "number": null,
    "council": "council:mid-america",
    "section": "G5",
    "region": "G",
    "hq_city": "Omaha",
    "hq_state": "NE",
    "lat": 41.2917293,
    "lon": -96.1063447,
    "website": "http://mac-oa.org"
  },
  {
    "slug": "puvunga",
    "name": "Puvunga",
    "number": null,
    "council": "council:long-beach-area",
    "section": "G18S",
    "region": "G",
    "hq_city": "Long Beach",
    "hq_state": "CA",
    "lat": 33.8244563,
    "lon": -118.1876533,
    "website": "https://www.longbeachbsa.org/activities/oa"
  },
  {
    "slug": "quelqueshoe",
    "name": "Quelqueshoe",
    "number": null,
    "council": "council:calcasieu-area",
    "section": "G1",
    "region": "G",
    "hq_city": "Lake Charles",
    "hq_state": "LA",
    "lat": 30.2164571,
    "lon": -93.22472929999999,
    "website": "http://www.quelqueshoe.org"
  },
  {
    "slug": "quinipissa",
    "name": "Quinipissa",
    "number": null,
    "council": "council:istrouma-area",
    "section": "G1",
    "region": "G",
    "hq_city": "Baton Rouge",
    "hq_state": "LA",
    "lat": 30.4093772,
    "lon": -91.077989,
    "website": "https://quinipissalodge479.org"
  },
  {
    "slug": "sac-n-fox",
    "name": "Sac-N-Fox",
    "number": null,
    "council": "council:winnebago",
    "section": "G8",
    "region": "G",
    "hq_city": "Waterloo",
    "hq_state": "IA",
    "lat": 42.5406528,
    "lon": -92.3963856,
    "website": "http://sacnfoxlodge.org"
  },
  {
    "slug": "sakima",
    "name": "Sakima",
    "number": null,
    "council": "council:la-salle",
    "section": "E1",
    "region": "E",
    "hq_city": "South Bend",
    "hq_state": "IN",
    "lat": 41.69082,
    "lon": -86.2290093,
    "website": "http://www.lasallecouncilbsa.org/sakimalodge"
  },
  {
    "slug": "saklan",
    "name": "Saklan",
    "number": null,
    "council": "council:silicon-valley-monterey-bay",
    "section": "G17S",
    "region": "G",
    "hq_city": "San Jose",
    "hq_state": "CA",
    "lat": 37.3412306,
    "lon": -121.9228357,
    "website": "https://saklanlodge.org/saklan"
  },
  {
    "slug": "sasquesahanough",
    "name": "Sasquesahanough",
    "number": null,
    "council": "council:new-birth-of-freedom",
    "section": "E11",
    "region": "E",
    "hq_city": "Mechanicsburg",
    "hq_state": "PA",
    "lat": 40.2505814,
    "lon": -77.0289854,
    "website": "https://sasquesahanough.org"
  },
  {
    "slug": "sebooney-okasucca",
    "name": "Sebooney Okasucca",
    "number": null,
    "council": "council:mississippi-riverlands",
    "section": "E4",
    "region": "E",
    "hq_city": "Jackson",
    "hq_state": "MS",
    "lat": 32.3228775,
    "lon": -90.17245009999999,
    "website": "https://sebooneyokasucca.org"
  },
  {
    "slug": "semialachee",
    "name": "Semialachee",
    "number": null,
    "council": "council:suwannee-river-area",
    "section": "E5",
    "region": "E",
    "hq_city": "Tallahassee",
    "hq_state": "FL",
    "lat": 30.4688389,
    "lon": -84.2679433,
    "website": "http://semialacheelodge.com"
  },
  {
    "slug": "sequoyah",
    "name": "Sequoyah",
    "number": null,
    "council": "council:sequoyah",
    "section": "E3",
    "region": "E",
    "hq_city": "Johnson City",
    "hq_state": "TN",
    "lat": 36.3828862,
    "lon": -82.42506209999999,
    "website": "http://www.sequoyahlodge184.org"
  },
  {
    "slug": "shawnee",
    "name": "Shawnee",
    "number": null,
    "council": "council:greater-saint-louis-area",
    "section": "G7",
    "region": "G",
    "hq_city": "Chesterfield",
    "hq_state": "MO",
    "lat": 38.6291495,
    "lon": -90.5184984,
    "website": "http://shawneelodge.org"
  },
  {
    "slug": "shenandoah",
    "name": "Shenandoah",
    "number": null,
    "council": "council:virginia-headwaters",
    "section": "E9",
    "region": "E",
    "hq_city": "Staunton",
    "hq_state": "VA",
    "lat": 38.1383686,
    "lon": -79.06904209999999,
    "website": "http://www.shenandoahlodge.org"
  },
  {
    "slug": "shinnecock",
    "name": "Shinnecock",
    "number": null,
    "council": "council:suffolk-county",
    "section": "E18",
    "region": "E",
    "hq_city": "Farmingville",
    "hq_state": "NY",
    "lat": 40.844015,
    "lon": -73.01635999999999,
    "website": "https://www.sccbsa.org/oa"
  },
  {
    "slug": "shunkah-mahneetu",
    "name": "Shunkah Mahneetu",
    "number": null,
    "council": "council:grand-teton",
    "section": "G14",
    "region": "G",
    "hq_city": "Idaho Falls",
    "hq_state": "ID",
    "lat": 43.4939582,
    "lon": -112.0218497,
    "website": "http://www.tetonscouts.org/oa"
  },
  {
    "slug": "sikhs-mox-lamonti",
    "name": "Sikhs Mox Lamonti",
    "number": null,
    "council": "council:mount-baker",
    "section": "G15",
    "region": "G",
    "hq_city": "Marysville",
    "hq_state": "WA",
    "lat": 48.0563616,
    "lon": -122.1492224,
    "website": "http://mountbakerbsa.org/camps/order-of-the-arrow"
  },
  {
    "slug": "sipp-o",
    "name": "Sipp-O",
    "number": null,
    "council": "council:buckeye",
    "section": "E13",
    "region": "E",
    "hq_city": "Canton",
    "hq_state": "OH",
    "lat": 40.8118699,
    "lon": -81.39855539999999,
    "website": "https://www.buckeyecouncil.org/order-of-the-arrow"
  },
  {
    "slug": "skyuka",
    "name": "Skyuka",
    "number": null,
    "council": "council:palmetto-area",
    "section": "E7",
    "region": "E",
    "hq_city": "Spartanburg",
    "hq_state": "SC",
    "lat": 34.9409181,
    "lon": -81.9281731,
    "website": "http://www.skyukalodge.org"
  },
  {
    "slug": "southern-prairie",
    "name": "Southern Prairie",
    "number": null,
    "council": "council:last-frontier",
    "section": "G4",
    "region": "G",
    "hq_city": "Oklahoma City",
    "hq_state": "OK",
    "lat": 35.5377149,
    "lon": -97.567976,
    "website": "https://southernprairie.org"
  },
  {
    "slug": "spe-le-yai",
    "name": "Spe-Le-Yai",
    "number": null,
    "council": "council:verdugo-hills",
    "section": "G18N",
    "region": "G",
    "hq_city": "Glendale",
    "hq_state": "CA",
    "lat": 34.1525699,
    "lon": -118.2446095,
    "website": null
  },
  {
    "slug": "t-kope-kwiskwis",
    "name": "T'Kope Kwiskwis",
    "number": null,
    "council": "council:chief-seattle",
    "section": "G15",
    "region": "G",
    "hq_city": "Seattle",
    "hq_state": "WA",
    "lat": 47.5751876,
    "lon": -122.2950134,
    "website": "https://tkopekwiskwis.org"
  },
  {
    "slug": "ta-tsu-hwa",
    "name": "Ta Tsu Hwa",
    "number": null,
    "council": "council:indian-nations",
    "section": "G4",
    "region": "G",
    "hq_city": "Tulsa",
    "hq_state": "OK",
    "lat": 36.1020674,
    "lon": -95.8506882,
    "website": "http://www.tatsuhwa.org"
  },
  {
    "slug": "tah-heetch",
    "name": "Tah-Heetch",
    "number": null,
    "council": "council:sequoia",
    "section": "G17S",
    "region": "G",
    "hq_city": "Fresno",
    "hq_state": "CA",
    "lat": 36.8232319,
    "lon": -119.8532238,
    "website": "http://www.tah-heetch.org"
  },
  {
    "slug": "tahosa",
    "name": "Tahosa",
    "number": null,
    "council": "council:greater-colorado",
    "section": "G12S",
    "region": "G",
    "hq_city": "Denver",
    "hq_state": "CO",
    "lat": 39.7263312,
    "lon": -105.1155398,
    "website": "http://tahosalodge.org"
  },
  {
    "slug": "takachsin",
    "name": "Takachsin",
    "number": null,
    "council": "council:sagamore",
    "section": "E1",
    "region": "E",
    "hq_city": "Kokomo",
    "hq_state": "IN",
    "lat": 40.52,
    "lon": -86.17999999999999,
    "website": "http://www.takachsin.org"
  },
  {
    "slug": "takhone",
    "name": "Takhone",
    "number": null,
    "council": "council:pathway-to-adventure",
    "section": "G9",
    "region": "G",
    "hq_city": "Chicago",
    "hq_state": "IL",
    "lat": 41.8833004,
    "lon": -87.6546455,
    "website": "http://www.oa7.org"
  },
  {
    "slug": "takhonek",
    "name": "Takhonek",
    "number": null,
    "council": "council:buckskin",
    "section": "E13",
    "region": "E",
    "hq_city": "Charleston",
    "hq_state": "WV",
    "lat": 38.3312423,
    "lon": -81.5846792,
    "website": "http://www.buckskin.org/oa"
  },
  {
    "slug": "talako",
    "name": "Talako",
    "number": null,
    "council": "council:marin",
    "section": "G17N",
    "region": "G",
    "hq_city": "San Rafael",
    "hq_state": "CA",
    "lat": 37.974163,
    "lon": -122.5426511,
    "website": "http://Talako.org"
  },
  {
    "slug": "talidandaganu",
    "name": "Talidandaganu'",
    "number": null,
    "council": "council:cherokee-area-556",
    "section": "E3",
    "region": "E",
    "hq_city": "Chattanooga",
    "hq_state": "TN",
    "lat": 35.0281606,
    "lon": -85.1900117,
    "website": "https://www.talidandaganu293.org"
  },
  {
    "slug": "tamegonit",
    "name": "Tamegonit",
    "number": null,
    "council": "council:heart-of-america",
    "section": "G6",
    "region": "G",
    "hq_city": "Kansas City",
    "hq_state": "MO",
    "lat": 38.9419967,
    "lon": -94.5836245,
    "website": "http://Tamegonit.net"
  },
  {
    "slug": "tannu",
    "name": "Tannu",
    "number": null,
    "council": "council:nevada-area",
    "section": "G17N",
    "region": "G",
    "hq_city": "Reno",
    "hq_state": "NV",
    "lat": 39.44106319999999,
    "lon": -119.7638212,
    "website": "https://nevadaareascouting.org/order-of-the-arrow"
  },
  {
    "slug": "tantamous",
    "name": "Tantamous",
    "number": null,
    "council": "council:mayflower",
    "section": "E19",
    "region": "E",
    "hq_city": "Milford",
    "hq_state": "MA",
    "lat": 42.158206,
    "lon": -71.50660359999999,
    "website": "http://tantamous.org"
  },
  {
    "slug": "tarhe",
    "name": "Tarhe",
    "number": null,
    "council": "council:tecumseh",
    "section": "E2",
    "region": "E",
    "hq_city": "Yellow Springs",
    "hq_state": "OH",
    "lat": 39.7952223,
    "lon": -83.854376,
    "website": "http://www.tarhe292.org"
  },
  {
    "slug": "tatanka",
    "name": "Tatanka",
    "number": null,
    "council": "council:buffalo-trail",
    "section": "G2",
    "region": "G",
    "hq_city": "Midland",
    "hq_state": "TX",
    "lat": 31.9971808,
    "lon": -102.0862004,
    "website": "http://www.tatanka141.org"
  },
  {
    "slug": "tecumseh",
    "name": "Tecumseh",
    "number": null,
    "council": "council:simon-kenton",
    "section": "E13",
    "region": "E",
    "hq_city": "Columbus",
    "hq_state": "OH",
    "lat": 39.9971454,
    "lon": -83.0301709,
    "website": "http://www.tecumseh65.org"
  },
  {
    "slug": "tejas",
    "name": "Tejas",
    "number": null,
    "council": "council:east-texas-area",
    "section": "G3",
    "region": "G",
    "hq_city": "Tyler",
    "hq_state": "TX",
    "lat": 32.332158,
    "lon": -95.2847263,
    "website": "https://tejaslodge72.org"
  },
  {
    "slug": "tetonwana",
    "name": "Tetonwana",
    "number": null,
    "council": "council:sioux",
    "section": "G11",
    "region": "G",
    "hq_city": "Sioux Falls",
    "hq_state": "SD",
    "lat": 43.5565349,
    "lon": -96.7462075,
    "website": "http://www.siouxcouncil.org/oa"
  },
  {
    "slug": "ti-ak",
    "name": "Ti'ak",
    "number": null,
    "council": "council:pine-burr-area",
    "section": "E4",
    "region": "E",
    "hq_city": "Hattiesburg",
    "hq_state": "MS",
    "lat": 31.3244471,
    "lon": -89.3116703,
    "website": "http://www.pineburrscouts.org/lodge"
  },
  {
    "slug": "timmeu",
    "name": "Timmeu",
    "number": null,
    "council": "council:northeast-iowa",
    "section": "G8",
    "region": "G",
    "hq_city": "Dubuque",
    "hq_state": "IA",
    "lat": 42.4458233,
    "lon": -90.68767799999999,
    "website": "http://www.scoutsiowa.org/order-of-the-arrow"
  },
  {
    "slug": "tindeuchen",
    "name": "Tindeuchen",
    "number": null,
    "council": "council:erie-shores",
    "section": "E2",
    "region": "E",
    "hq_city": "Toledo",
    "hq_state": "OH",
    "lat": 41.6998261,
    "lon": -83.6508025,
    "website": "https://www.tindeuchenlodge.com"
  },
  {
    "slug": "tipisa",
    "name": "Tipisa",
    "number": null,
    "council": "council:central-florida",
    "section": "E5",
    "region": "E",
    "hq_city": "Apopka",
    "hq_state": "FL",
    "lat": 28.6485315,
    "lon": -81.4604763,
    "website": "http://www.tipisa.org"
  },
  {
    "slug": "tiwahe",
    "name": "Tiwahe",
    "number": null,
    "council": "council:san-diego-imperial",
    "section": "G13W",
    "region": "G",
    "hq_city": "San Diego",
    "hq_state": "CA",
    "lat": 32.7402117,
    "lon": -117.1535176,
    "website": "https://tiwahelodge.org"
  },
  {
    "slug": "toloma",
    "name": "Toloma",
    "number": null,
    "council": "council:greater-yosemite",
    "section": "G17S",
    "region": "G",
    "hq_city": "Modesto",
    "hq_state": "CA",
    "lat": 37.7094291,
    "lon": -121.0700901,
    "website": "http://www.toloma.org"
  },
  {
    "slug": "tom-kita-chara",
    "name": "Tom Kita Chara",
    "number": null,
    "council": "council:samoset",
    "section": "G10",
    "region": "G",
    "hq_city": "Weston",
    "hq_state": "WI",
    "lat": 44.9243013,
    "lon": -89.57113969999999,
    "website": "http://tkclodge.org"
  },
  {
    "slug": "tonkawa",
    "name": "Tonkawa",
    "number": null,
    "council": "council:capitol-area",
    "section": "G2",
    "region": "G",
    "hq_city": "Austin",
    "hq_state": "TX",
    "lat": 30.4057864,
    "lon": -97.6760917,
    "website": "http://www.tonkawa99.org"
  },
  {
    "slug": "toontuk",
    "name": "Toontuk",
    "number": null,
    "council": "council:midnight-sun",
    "section": "G15",
    "region": "G",
    "hq_city": "Fairbanks",
    "hq_state": "AK",
    "lat": 64.8355282,
    "lon": -147.7278538,
    "website": null
  },
  {
    "slug": "topa-topa",
    "name": "Topa Topa",
    "number": null,
    "council": "council:ventura-county",
    "section": "G18N",
    "region": "G",
    "hq_city": "Camarillo",
    "hq_state": "CA",
    "lat": 34.2194221,
    "lon": -119.063357,
    "website": "https://topatopa.org"
  },
  {
    "slug": "totanhan-nakaha",
    "name": "Totanhan Nakaha",
    "number": null,
    "council": "council:northern-star",
    "section": "G11",
    "region": "G",
    "hq_city": "Fort Snelling",
    "hq_state": "MN",
    "lat": 44.8936284,
    "lon": -93.1931479,
    "website": "https://tnl-oa.org"
  },
  {
    "slug": "tsali",
    "name": "Tsali",
    "number": null,
    "council": "council:daniel-boone",
    "section": "E7",
    "region": "E",
    "hq_city": "Asheville",
    "hq_state": "NC",
    "lat": 35.5917698,
    "lon": -82.56436959999999,
    "website": "http://www.tsalilodge.org"
  },
  {
    "slug": "tschipey-achtu",
    "name": "Tschipey Achtu",
    "number": null,
    "council": "council:seneca-waterways",
    "section": "E15",
    "region": "E",
    "hq_city": "Rochester",
    "hq_state": "NY",
    "lat": 43.0956226,
    "lon": -77.6159057,
    "website": "http://www.senecawaterways.org/oa"
  },
  {
    "slug": "tschitani",
    "name": "Tschitani",
    "number": null,
    "council": "council:connecticut-rivers",
    "section": "E20",
    "region": "E",
    "hq_city": "East Hartford",
    "hq_state": "CT",
    "lat": 41.7671242,
    "lon": -72.65877309999999,
    "website": "https://www.tschitani.org"
  },
  {
    "slug": "tsoiotsi-tsogalii",
    "name": "Tsoiotsi Tsogalii",
    "number": null,
    "council": "council:old-north-state",
    "section": "E8",
    "region": "E",
    "hq_city": "Greensboro",
    "hq_state": "NC",
    "lat": 36.0894401,
    "lon": -79.8154267,
    "website": "https://lodge70.org"
  },
  {
    "slug": "tukarica",
    "name": "Tukarica",
    "number": null,
    "council": "council:mountain-west",
    "section": "G14",
    "region": "G",
    "hq_city": "Boise",
    "hq_state": "ID",
    "lat": 43.604487,
    "lon": -116.2925665,
    "website": "http://www.mountainwestcouncil.org/tukaricahomepage"
  },
  {
    "slug": "tuku-ut",
    "name": "Tuku'ut",
    "number": null,
    "council": "council:greater-los-angeles-area",
    "section": "G18N",
    "region": "G",
    "hq_city": "Los Angeles",
    "hq_state": "CA",
    "lat": 34.0730149,
    "lon": -118.2707137,
    "website": "https://www.tukuut.org"
  },
  {
    "slug": "tulpe",
    "name": "Tulpe",
    "number": null,
    "council": "council:narragansett",
    "section": "E19",
    "region": "E",
    "hq_city": "Cranston",
    "hq_state": "RI",
    "lat": 41.7791615,
    "lon": -71.48428750000001,
    "website": "http://www.tulpelodge.org"
  },
  {
    "slug": "tutelo",
    "name": "Tutelo",
    "number": null,
    "council": "council:blue-ridge-mountains",
    "section": "E9",
    "region": "E",
    "hq_city": "Roanoke",
    "hq_state": "VA",
    "lat": 37.3490124,
    "lon": -79.95284509999999,
    "website": "https://tutelo161.org"
  },
  {
    "slug": "uh-to-yeh-hut-tee",
    "name": "Uh-To-Yeh-Hut-Tee",
    "number": null,
    "council": "council:greater-tampa-bay-area",
    "section": "E5",
    "region": "E",
    "hq_city": "Tampa",
    "hq_state": "FL",
    "lat": 28.0669512,
    "lon": -82.4558455,
    "website": "http://www.uhtoyehhuttee.org"
  },
  {
    "slug": "unali-yi",
    "name": "Unali'Yi",
    "number": null,
    "council": "council:coastal-carolina",
    "section": "E7",
    "region": "E",
    "hq_city": "N. Charleston",
    "hq_state": "SC",
    "lat": 32.9761645,
    "lon": -80.07581619999999,
    "website": "http://site236.com"
  },
  {
    "slug": "unami",
    "name": "Unami",
    "number": null,
    "council": "council:cradle-of-liberty",
    "section": "E17",
    "region": "E",
    "hq_city": "King of Prussia",
    "hq_state": "PA",
    "lat": 40.09920899999999,
    "lon": -75.408861,
    "website": "http://www.unamilodge.org"
  },
  {
    "slug": "wa-hi-nasa",
    "name": "Wa-Hi-Nasa",
    "number": null,
    "council": "council:middle-tennessee",
    "section": "E3",
    "region": "E",
    "hq_city": "Nashville",
    "hq_state": "TN",
    "lat": 36.0452032,
    "lon": -86.86454069999999,
    "website": "http://wa-hi-nasa.org"
  },
  {
    "slug": "wag-o-shag",
    "name": "Wag-O-Shag",
    "number": null,
    "council": "council:potawatomi-area",
    "section": "G9",
    "region": "G",
    "hq_city": "Waukesha",
    "hq_state": "WI",
    "lat": 43.0476676,
    "lon": -88.2353294,
    "website": "http://wagoshag.com"
  },
  {
    "slug": "wagion",
    "name": "Wagion",
    "number": null,
    "council": "council:westmoreland-fayette",
    "section": "E21",
    "region": "E",
    "hq_city": "Greensburg",
    "hq_state": "PA",
    "lat": 40.3260558,
    "lon": -79.5455678,
    "website": "http://www.wagion.org"
  },
  {
    "slug": "waguli",
    "name": "Waguli",
    "number": null,
    "council": "council:northwest-georgia",
    "section": "E6",
    "region": "E",
    "hq_city": "Rome",
    "hq_state": "GA",
    "lat": 34.2514697,
    "lon": -85.1737775,
    "website": "http://www.waguli.com"
  },
  {
    "slug": "wah-sha-she",
    "name": "Wah-Sha-She",
    "number": null,
    "council": "council:ozark-trails",
    "section": "G6",
    "region": "G",
    "hq_city": "Springfield",
    "hq_state": "MO",
    "lat": 37.1834993,
    "lon": -93.2234993,
    "website": "http://www.wahshashe.org"
  },
  {
    "slug": "wahinkto",
    "name": "Wahinkto",
    "number": null,
    "council": "council:texas-southwest",
    "section": "G2",
    "region": "G",
    "hq_city": "San Angelo",
    "hq_state": "TX",
    "lat": 31.4582307,
    "lon": -100.4375783,
    "website": "https://tswcbsa.org/order-of-the-arrow"
  },
  {
    "slug": "wahissa",
    "name": "Wahissa",
    "number": null,
    "council": "council:old-hickory",
    "section": "E8",
    "region": "E",
    "hq_city": "Winston-Salem",
    "hq_state": "NC",
    "lat": 36.1311958,
    "lon": -80.2922492,
    "website": "http://www.wahissa.org"
  },
  {
    "slug": "wahpekute",
    "name": "Wahpekute",
    "number": null,
    "council": "council:twin-valley",
    "section": "G11",
    "region": "G",
    "hq_city": "Mankato",
    "hq_state": "MN",
    "lat": 44.1684829,
    "lon": -93.98574459999999,
    "website": null
  },
  {
    "slug": "wahunsenakah",
    "name": "Wahunsenakah",
    "number": null,
    "council": "council:colonial-virginia",
    "section": "E9",
    "region": "E",
    "hq_city": "Newport News",
    "hq_state": "VA",
    "lat": 37.0805565,
    "lon": -76.4797597,
    "website": "http://www.wahunsenakah.org"
  },
  {
    "slug": "walamootkin",
    "name": "Walamootkin",
    "number": null,
    "council": "council:blue-mountain",
    "section": "G14",
    "region": "G",
    "hq_city": "Kennewick",
    "hq_state": "WA",
    "lat": 46.22743560000001,
    "lon": -119.2344031,
    "website": "https://walamootkinlodge.org"
  },
  {
    "slug": "washita",
    "name": "Washita",
    "number": null,
    "council": "council:cherokee-area",
    "section": "G4",
    "region": "G",
    "hq_city": "Bartlesville",
    "hq_state": "OK",
    "lat": 36.7466904,
    "lon": -95.963556,
    "website": "https://cherokeebsa.org/washita-lodge"
  },
  {
    "slug": "wauna-la-mon-tay",
    "name": "Wauna La-Mon'Tay",
    "number": null,
    "council": "council:cascade-pacific",
    "section": "G16",
    "region": "G",
    "hq_city": "Portland",
    "hq_state": "OR",
    "lat": 45.5073419,
    "lon": -122.6782415,
    "website": "https://cpc-oa.org"
  },
  {
    "slug": "waupecan",
    "name": "Waupecan",
    "number": null,
    "council": "council:rainbow",
    "section": "G9",
    "region": "G",
    "hq_city": "Morris",
    "hq_state": "IL",
    "lat": 41.3255904,
    "lon": -88.3421343,
    "website": "http://www.oa197.org"
  },
  {
    "slug": "wenasa-quenhotan",
    "name": "Wenasa Quenhotan",
    "number": null,
    "council": "council:w-d-boyce",
    "section": "G8",
    "region": "G",
    "hq_city": "Peoria",
    "hq_state": "IL",
    "lat": 40.6978908,
    "lon": -89.584538,
    "website": "https://wq23.org"
  },
  {
    "slug": "wewanoma",
    "name": "Wewanoma",
    "number": null,
    "council": "council:rio-grande",
    "section": "G2",
    "region": "G",
    "hq_city": "Harlingen",
    "hq_state": "TX",
    "lat": 26.1878131,
    "lon": -97.7614526,
    "website": "https://wewanoma.org"
  },
  {
    "slug": "wiatava",
    "name": "Wiatava",
    "number": null,
    "council": "council:orange-county",
    "section": "G18S",
    "region": "G",
    "hq_city": "Orange",
    "hq_state": "CA",
    "lat": 33.8028576,
    "lon": -117.7539527,
    "website": "https://wiatava.ocbsa.org"
  },
  {
    "slug": "wichita",
    "name": "Wichita",
    "number": null,
    "council": "council:northwest-texas",
    "section": "G3",
    "region": "G",
    "hq_city": "Wichita Falls",
    "hq_state": "TX",
    "lat": 33.8743675,
    "lon": -98.5305767,
    "website": null
  },
  {
    "slug": "wihinipa-hinsa",
    "name": "Wihinipa Hinsa",
    "number": null,
    "council": "council:bay-area",
    "section": "G2",
    "region": "G",
    "hq_city": "Galveston",
    "hq_state": "TX",
    "lat": 29.27341119999999,
    "lon": -94.8198804,
    "website": "http://www.bacbsa.org/order-of-the-arrow/69191"
  },
  {
    "slug": "wipala-wiki",
    "name": "Wipala Wiki",
    "number": null,
    "council": "council:grand-canyon",
    "section": "G13W",
    "region": "G",
    "hq_city": "Scottsdale",
    "hq_state": "AZ",
    "lat": 33.5127802,
    "lon": -111.8908104,
    "website": "https://oa.grandcanyonbsa.org"
  },
  {
    "slug": "wisawanik",
    "name": "Wisawanik",
    "number": null,
    "council": "council:arbuckle-area",
    "section": "G4",
    "region": "G",
    "hq_city": "Ardmore",
    "hq_state": "OK",
    "lat": 34.2035828,
    "lon": -97.1296747,
    "website": null
  },
  {
    "slug": "witauchsoman",
    "name": "Witauchsoman",
    "number": null,
    "council": "council:minsi-trails",
    "section": "E17",
    "region": "E",
    "hq_city": "Allentown",
    "hq_state": "PA",
    "lat": 40.64597759999999,
    "lon": -75.4384745,
    "website": "https://www.witauchsoman.org"
  },
  {
    "slug": "withlacoochee",
    "name": "Withlacoochee",
    "number": null,
    "council": "council:south-georgia",
    "section": "E6",
    "region": "E",
    "hq_city": "Valdosta",
    "hq_state": "GA",
    "lat": 30.8461025,
    "lon": -83.3179838,
    "website": "https://sites.google.com/view/withlacoochee-lodge"
  },
  {
    "slug": "woa-cholena",
    "name": "Woa Cholena",
    "number": null,
    "council": "council:mobile-area",
    "section": "E4",
    "region": "E",
    "hq_city": "Mobile",
    "hq_state": "AL",
    "lat": 30.6685899,
    "lon": -88.10292590000002,
    "website": "http://www.facebook.com/WoaCholena322"
  },
  {
    "slug": "woapalanne",
    "name": "Woapalanne",
    "number": null,
    "council": "council:patriots-path",
    "section": "E17",
    "region": "E",
    "hq_city": "Cedar Knolls",
    "hq_state": "NJ",
    "lat": 40.8141087,
    "lon": -74.4646961,
    "website": "https://ppcscouting.org/oa"
  },
  {
    "slug": "woapeu-sisilija",
    "name": "Woapeu Sisilija",
    "number": null,
    "council": "council:susquehanna",
    "section": "E11",
    "region": "E",
    "hq_city": "Williamsport",
    "hq_state": "PA",
    "lat": 41.25281409999999,
    "lon": -76.97175109999999,
    "website": null
  },
  {
    "slug": "woapink",
    "name": "Woapink",
    "number": null,
    "council": "council:greater-saint-louis-area",
    "section": "G7",
    "region": "G",
    "hq_city": "Chesterfield",
    "hq_state": "MO",
    "lat": 38.6291495,
    "lon": -90.5184984,
    "website": "http://www.woapink.org"
  },
  {
    "slug": "wulapeju",
    "name": "Wulapeju",
    "number": null,
    "council": "council:blackhawk-area",
    "section": "G9",
    "region": "G",
    "hq_city": "Rockford",
    "hq_state": "IL",
    "lat": 42.3020152,
    "lon": -88.9784067,
    "website": "https://tinyurl.com/wulapejulodge140"
  },
  {
    "slug": "wunita-gokhos",
    "name": "Wunita Gokhos",
    "number": null,
    "council": "council:pennsylvania-dutch",
    "section": "E11",
    "region": "E",
    "hq_city": "Lancaster",
    "hq_state": "PA",
    "lat": 40.0557818,
    "lon": -76.2969111,
    "website": "http://www.wg39.org"
  },
  {
    "slug": "wyona",
    "name": "Wyona",
    "number": null,
    "council": "council:columbia-montour",
    "section": "E11",
    "region": "E",
    "hq_city": "Bloomsburg",
    "hq_state": "PA",
    "lat": 41.0284425,
    "lon": -76.3409206,
    "website": "http://www.columbiamontourbsa.org/oawyona18"
  },
  {
    "slug": "yerba-buena",
    "name": "Yerba Buena",
    "number": null,
    "council": "council:golden-gate-area",
    "section": "G17N",
    "region": "G",
    "hq_city": "Pleasanton",
    "hq_state": "CA",
    "lat": 37.6978979,
    "lon": -121.90804,
    "website": "https://yerbabuena.goldengatescouting.org"
  },
  {
    "slug": "yokahu",
    "name": "Yokahu",
    "number": null,
    "council": "council:puerto-rico",
    "section": "E17",
    "region": "E",
    "hq_city": "Guaynabo",
    "hq_state": "PR",
    "lat": 18.371987,
    "lon": -66.107062,
    "website": "http://www.yokahu506.org"
  },
  {
    "slug": "yowlumne",
    "name": "Yowlumne",
    "number": null,
    "council": "council:southern-sierra",
    "section": "G18N",
    "region": "G",
    "hq_city": "Bakersfield",
    "hq_state": "CA",
    "lat": 35.3818539,
    "lon": -119.015604,
    "website": "http://www.yowlumne.org"
  },
  {
    "slug": "yustaga",
    "name": "Yustaga",
    "number": null,
    "council": "council:gulf-coast",
    "section": "E4",
    "region": "E",
    "hq_city": "Pensacola",
    "hq_state": "FL",
    "lat": 30.5354897,
    "lon": -87.22056239999999,
    "website": "http://www.yustaga385.org"
  }
]
""")


def main() -> None:
    out_dir = Path(__file__).resolve().parents[1] / "data" / "oa-lodges"
    out_dir.mkdir(parents=True, exist_ok=True)
    for r in LODGES:
        version = {
            "valid_from": None,
            "valid_to": None,
            "name": r["name"],
            "number": r["number"],
            "council": r["council"],
            "section": r["section"],
            "region": r["region"],
            "hq_city": r["hq_city"],
            "hq_state": r["hq_state"],
            "lat": r["lat"],
            "lon": r["lon"],
            "website": r["website"],
            "provenance": {
                "sources": [{"url": FEED_URL}],
                "method": "official_publication",
                "verified_at": VERIFIED_AT,
                "confidence": 1.0,
                "notes": NOTES,
            },
        }
        doc = {"id": r["slug"], "kind": "oa-lodge", "versions": [version], "notes": None}
        (out_dir / f"{r['slug']}.json").write_text(
            json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    print(f"oa-lodges: {len(LODGES)} lodge entities written")


if __name__ == "__main__":
    main()
